### ISSUE TITLE
운동량 변화량 API 테스트 코드 구현

### ISSUE THREAD

**Issue by ffinn92** [TeamCaleFIT/calefit-BE#1]
## 💡 Issue

운동량 변화량 API 3개에 대한 테스트 코드를 구현해야 한다.

## 📝 Todo

- [ ] 골격근 변화량 API 테스트 코드 구현
- [ ] 체지방 변화량 API 테스트 코드 구현
- [ ] 몸무게 변화량 API 테스트 코드 구현
