### ISSUE TITLE
Crew 추가 API 구현

### ISSUE THREAD

**Issue by ffinn92** [TeamCaleFIT/calefit-BE#11]
## 💡 Issue

Crew의 CRUD외에 비즈니스 요구사항에 따른 추가 API를 구현해야 한다.

## 📝 Todo

- [ ] Crew 상세 조회 API 구현
- [ ] 가입한 Crew 조회 API 구현
- [ ] 추천 Crew 조회 API 구현
- [ ] 검색한 Crew 조회 API 구현
