### ISSUE TITLE
Crew 도메인 Test 코드 작성

### ISSUE THREAD

**Issue by ffinn92** [TeamCaleFIT/calefit-BE#15]
## 💡 Issue

구현한 Crew 도메인의 API에 대한 Test 코드를 작성해야한다.

## 📝 Todo

- [ ] Crew 생성 API Test 코드 작성
- [ ] Crew 조회 API Test 코드 작성
- [ ] Crew 수정 API Test 코드 작성
- [ ] Crew 삭제 API Test 코드 작성
- [ ] Crew 상세 조회 API Test 코드 작성
- [ ] 가입한 Crew 조회 API Test 코드 작성
- [ ] 추천 Crew 조회 API Test 코드 작성
