### ISSUE TITLE
인바디 API 테스트 코드 구현

### ISSUE THREAD

**Issue by NB993** [TeamCaleFIT/calefit-BE#2]
## 💡 Issue

인바디 crud에 대한 api 테스트 코드를 작성한다.

## 📝 Todo
- [x] 인바디 추가 api 테스트 코드 작성
- [x] 인바디 삭제 api 테스트 코드 작성
- [x] 인바디 수정 api 테스트 코드 작성
- [x] 인바디 조회 api 테스트 코드 작성
