### ISSUE TITLE
Member 프로필 조회, 회원가입 API 구현

### ISSUE THREAD

**Issue by ffinn92** [TeamCaleFIT/calefit-BE#20]
## 💡 Issue

어플 사용자의 마이페이지를 접속하기 위해 프로필 조회 기능과 이용을 위한 회원가입 기능을 구현해야한다.

## 📝 Todo

- [x] Member 프로필 조회 API 구현
- [x] Member 프로필 조회 API 테스트 코드 작성
- [x] Member 프로필 조회 API 예외처리
- [x] Member 회원가입 API 구현
- [x] Member 회원가입 API 테스트 코드 작성
- [x] Member 회원가입 API 예외처리
