### ISSUE TITLE
인바디 API 구현

### ISSUE THREAD

**Issue by NB993** [TeamCaleFIT/calefit-BE#3]
## 💡 Issue

인바디 crud에 대한 api 를 작성한다.

## 📝 Todo

- [x] 인바디 그래프 조회 api 작성
- [x] 인바디 추가 api 작성
- [x] 인바디 삭제 api 작성
- [x] 인바디 수정 api 작성
